/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.orionline.gui;

import br.com.orionline.util.LoadProperties;
import com.alee.extended.filechooser.WebDirectoryChooser;
import com.alee.extended.filechooser.WebPathField;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author ronald
 */
public class DialogConfDB extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(DialogConfDB.class);
    WebDirectoryChooser fc;
    Properties dbProp = new Properties();
    LoadProperties props = new LoadProperties();

    /**
     * Creates new form DialogSobre
     */
    public DialogConfDB(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        logger.debug("Carregando componente da janela de configuração do banco de dados");
        initComponents();
        logger.debug("Componentes da janela de configuração do banco de dados carregados com sucesso!");
        File arqConf = new File("./properties/db.properties");
        if (arqConf.exists()) {
            String dirDB = props.getPropriedade("caminhoDB");
            if (!dirDB.isEmpty()) {
                lbCaminhoDB.setText(dirDB);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbCaminhoDB = new javax.swing.JTextField();
        btnAbrirDataBase = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OrionLine Automação Comercial");
        setIconImage(null);
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Caminho do banco de dados");

        btnAbrirDataBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/orionline/imagens/Open16.gif"))); // NOI18N
        btnAbrirDataBase.setText("Abrir");
        btnAbrirDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirDataBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 223, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCaminhoDB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbrirDataBase)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCaminhoDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrirDataBase))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnGravar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 173));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (lbCaminhoDB.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor Configure o banco de dados!");
        } else {
            FileOutputStream out = null;
            dbProp.setProperty("caminhoDB", lbCaminhoDB.getText());
            try {
                out = new FileOutputStream("./properties/db.properties");
            } catch (FileNotFoundException ex) {
                logger.error("Arquivo não encontrado", ex);
            }
            try {
                dbProp.store(out, "#####(Configuração do banco de Dados)##############");
            } catch (IOException ex) {
                logger.error("IOException", ex);
            }
            try {
                out.close();
            } catch (IOException ex) {
                logger.error("IOException", ex);
            }
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso!");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAbrirDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirDataBaseActionPerformed
        fc = new WebDirectoryChooser(this);
        fc.setDrawWatermark(true);
        fc.setModal(true);
        fc.setRound(5);
        fc.setShadeWidth(10);
        fc.setShowMaximizeButton(false);
        fc.setShowMinimizeButton(false);
        fc.setTitle("Selecione a pasta que contém os DBF's");
        fc.setEmptyTitleText("Testando EmptyTitleText");
        int result = fc.showDialog();
        if ( result == WebDirectoryChooser.OK_OPTION){
            File dirDB = fc.getSelectedDirectory();
            if (dirDB.exists()) {
                lbCaminhoDB.setText(dirDB.getPath());
            }
        }
        lbCaminhoDB.setCaretPosition(lbCaminhoDB.getDocument().getLength());
    }//GEN-LAST:event_btnAbrirDataBaseActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirDataBase;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lbCaminhoDB;
    // End of variables declaration//GEN-END:variables
}
